plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.gradleDownload)
}

android {
    namespace = "com.openipc.pixelpilot"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.openipc.pixelpilot"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "0.23.0"
    }

    signingConfigs {
        create("release") {
            storeFile = file("../fpv.jks")
            storePassword = "release"
            keyAlias = "fpv"
            keyPassword = "release"
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            signingConfig = signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding = true
    }
    androidResources {
        noCompress 'tflite'
    }
    buildToolsVersion '35.0.0'
    ndkVersion '26.1.10909125'
}

project.ext.ASSET_DIR = projectDir.toString() + '/src/main/assets'

task downloadModelFile0(type: de.undercouch.gradle.tasks.download.Download) {
    src 'https://storage.googleapis.com/mediapipe-models/object_detector/efficientdet_lite0/float32/1/efficientdet_lite0.tflite'
    dest project.ext.ASSET_DIR + '/efficientdet-lite0.tflite'
    overwrite false
}

task downloadModelFile1(type: de.undercouch.gradle.tasks.download.Download) {
    src 'https://storage.googleapis.com/mediapipe-models/object_detector/efficientdet_lite2/float32/1/efficientdet_lite2.tflite'
    dest project.ext.ASSET_DIR + '/efficientdet-lite2.tflite'
    overwrite false
}

preBuild.dependsOn downloadModelFile0, downloadModelFile1

dependencies {
    implementation(project(":app:mavlink"))
    implementation(project(":app:videonative"))
    implementation(project(":app:wfbngrtl8812"))

    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.philjay.mpandroidchart)
    implementation(libs.mediapipe.tasks.vision)
}
