name: Build
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    environment: ANDROID_KEYSTORE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > pixelpilot.jks

      - name: Build APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_PATH: ${{ github.workspace }}/pixelpilot.jks
        run: |
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=pixelpilot \
          -Pandroid.injected.signing.key.password=$KEYSTORE_PASSWORD
          mv app/build/outputs/apk/release/app-release.apk PixelPilot.apk

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
          files: PixelPilot.apk
